Задание 2: конкурентное программирование и пользовательский интерфейс
sergey-berezin/401_spiridonova pull request #2
Opened 2023-10-27 20:21 UTC by AlinaStudies

2023-10-31 13:04 UTC, sergey-berezin requested changes

2023-10-31 13:04 UTC, sergey-berezin commented on ONNXPackage/Network.cs
> +        public static void Annotate(Image<Rgb24> target, ObjectBox obj)
Этот метод не имеет отношения к компоненту с нейронной сетью. Гораздо больше похоже на метод ObjectBox.

2023-10-31 13:04 UTC, sergey-berezin commented on Lab 2/ViewModel/MainViewModel.cs
> +                        var task = DetectAsync(filename, cts);
Зачем запоминать результат в переменной task?

2023-11-01 16:45 UTC, AlinaStudies commented on ONNXPackage/Network.cs
> +        public static void Annotate(Image<Rgb24> target, ObjectBox obj)
Поправила: сделала методом ObjectBox.

2023-11-01 16:46 UTC, AlinaStudies commented on Lab 2/ViewModel/MainViewModel.cs
> +                        var task = DetectAsync(filename, cts);
Поправила.

2023-11-07 07:51 UTC, sergey-berezin approved these changes

2023-11-14 08:07 UTC, sergey-berezin commented
Все исправления приняты. Для сдачи второго задания вам надо прийти на занятие по технологической практике и показать работающую программу.

2023-11-29 12:21 UTC, sergey-berezin commented
Замечаний к PR нет. Для сдачи третьего задания вам надо прийти на занятие по технологической практике и показать работающую программу.

2023-12-12 07:18 UTC, merged